"""Add role column to users

Revision ID: 13178669ebb1
Revises: 7b4c7752ceef
Create Date: 2025-05-22 19:34:09.554385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13178669ebb1'
down_revision = '7b4c7752ceef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
