"""Add showtime to Booking

Revision ID: 60b51118d804
Revises: 13178669ebb1
Create Date: 2025-06-04 13:40:44.250238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b51118d804'
down_revision = '13178669ebb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('showtime', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'showtime')
    # ### end Alembic commands ###
