"""Add seats and email columns to bookings

Revision ID: 7b4c7752ceef
Revises: 
Create Date: 2025-05-22 18:53:45.131075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4c7752ceef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('seats', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('email', sa.String(length=120), nullable=False))
    op.drop_column('movies', 'rating')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.add_column('movies', sa.Column('rating', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'email')
    op.drop_column('bookings', 'seats')
    # ### end Alembic commands ###
